version: '3'

tasks:
  apply:
    desc: Runs Terraform apply (`-- -target='cloudflare_record.this'`)
    cmds:
      - terraform apply {{.CLI_ARGS}}
      - task: validate
  cost:
    desc: Estimates the cost of infrastructure (`-- -format=json` for JSON format)
    cmds:
      - infracost breakdown --path=./ {{.CLI_ARGS}}
  cost-readme:
    desc: Estimates the cost of the infrastructure and outputs into README.md
    cmds:
      # TODO: Make this path more dynamic
      - python ${HOME}/Code/benniemosher-dev/.github/scripts/replace.py --path={{.USER_WORKING_DIR}}
  destroy:
    desc: Runs Terraform destroy (`-- -target='cloudflare_record.this'`)
    cmds:
      - terraform destroy {{.CLI_ARGS}}
  docs:
    desc: Updates Terraform docs
    cmds:
      - terraform-docs markdown . --output-file=README.md
  init:
    desc: Initializes Terraform (`-- -upgrade` to upgrade providers)
    cmds:
      - terraform init {{.CLI_ARGS}}
      - tflint --init
  import:
    desc: Imports a resource into Terraform (`-- <TARGET> <IDENTIFIER>`)
    cmds:
      - terraform import {{.CLI_ARGS}}
  lint:
    desc: Lints Terraform
    cmds:
      - tflint
  plan:
    desc: Runs Terraform Plan (`-- -target='cloudflare_record.this'`)
    cmds:
      - terraform plan {{.CLI_ARGS}}
      - task: validate
  sec:
    desc: Validates security of Terraform resources
    cmds:
      - tfsec .
  validate:
    desc: Runs Terraform fmt, validate, docs, lint, sec, and cost-readme.
    cmds:
      - terraform fmt --recursive
      - terraform validate
      - task: docs
      - task: lint
      - task: sec
      - task: cost-readme
