name: Terraform CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  ci-terraform:
    name: Terraform CI
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@main"
    # with:
    #   enable-cost: false
