---
name: Terraform CI

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:
  ci-terraform:
    name: Terraform CI
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@5ca06cf92808c8beee39c82417374081374ee1b5" # main
    # with:
    #   enable-cost: false
