name: BennieMosher.dev CI Pre-Commit for Terraform

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  ci-terraform:
    name: Continuous Integration for Terraform
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform-pre-commit.yml@main"
    # with:
    #   enable-cost: false
